name: Release

on:
  push:
    branches: ['main']
    paths:
      - '**/package.json'
      - '.changeset/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 17
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install --immutable
    - uses: changesets/action@v1
      with:
        publish: yarn ci:release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
